# Generated by Django 4.1 on 2024-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_movie_actors_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
